### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [ytaros/Good_Spot_Kansai#128]
MVPリリースお疲れ様でした。

ページ表示までに時間がかかっている部分を改善できれば、すぐに就活に臨んで大丈夫なレベルでした！
就活の準備と並行して残りの実装、本リリースの機能に着手していきましょう！

（以下はMVPレビュー及びより良いサービスのための提案になります）

---

## READMEから課題解決する実装がされているか&動いている
こちら確認しました。LGTMです。

## より良いサービスのための提案
- ページ表示までにだいぶ時間がかかってしまっているので、以下の対応を検討してください（講師陣4名が確認のためにサービスを利用したところ、ページ表示まで時間がかかっていました。このレビューを記載している際はそのような現象にはなっていませんが、就活時にその現象が出てしまうとマイナスの印象を与えるので対策をしておくとベターです）
  - ①Renderの有料化
  - ②Herokuへの切り替え検討
- 初期データの充実を図る。
  - 現状データの無い県があったりと、データが少ない印象を受けるので、どの県でもサービスの利用ができる状態を整えておくとベターです。（RUNTEQ生に使ってもらって拡充を図る方法でも可です）
- ユーザー登録後、自動ログインさせましょう。（ここまで仕上がっているので、よりよいユーザー体験に向けての施策になります）
- 文言のところで少し検討いただきたい部分（採用するか否かはサービスの世界観と照らし合わせて検討ください）
  - 関西弁に寄せる。（ですます調の部分を無くして、関西弁に統一して世界観を更に出していく）

**Comment by ytaros** [comment]
お忙しい中ご確認いただきましてありがとうございました。
ページ表示の件、対応いたしましたら専用チャンネルにてご連絡差し上げます。
また、アドバイスいただきましたように自動ログイン、TOPページの改善後にMVPリリース周知した上でサービスの拡充を図ります。
